### ISSUE TITLE
brittle pg_id (ebookNumber) detection

### ISSUE THREAD

**Issue by eshellman** [gutenbergbooks/git#2]
This code:
  
`ebookNumber=$(ls *.txt | grep --extended-regexp --only-matching "^[0-9]+\.txt" | head -n 1 | sed "s/\.txt//g")`

https://github.com/gutenbergbooks/git/blob/master/init-pg-repo#L59

will fail for many repos, for example

https://github.com/GITenberg/Merirosvo_50266

There are a bunch of file layouts used in PG; It might be easier to have the script start with the ebookNumber rather than the directory location.

**Comment by acabal** [comment]
Good idea, I've updated the script to accept ebook IDs instead of directories.  I pulled in Greg's `pgpath.pl` to do the heavy lifting of generating ebook directory paths for us.

**Comment by eshellman** [comment]
wow, that was fast!
