### ISSUE TITLE
scaling to 50K books: rate limits and abuse detection.

### ISSUE THREAD

**Issue by eshellman** [gutenbergbooks/git#8]
Github imposes some rate limits.
1. Github API is limited to 5000 reqs/hour. It's easy in the python module to ratelimit, so I could write a python script that calls init-pg-repo and will run the 10 hours needed. Or @acabal can look at writing a shell script. 
2. Github abuse detection will flag the bot after a few thousand repos and disappear the entire organization. Gitenberg is on a whitelist. We should contact github support before running trying to load the 50,000 repos.

**Comment by acabal** [comment]
I can contact support; is there someone you already talked to in the past, whose contact info you can send me?  Or should I just use the generic contact form?

**Comment by eshellman** [comment]
github support is the right contact. You can quote this previous email:

**Comment by acabal** [comment]
I've been chatting with Github support and they've whitelisted this org in their spam checks, so that should be that!
