### ISSUE TITLE
Consider setting downloads to true

### ISSUE THREAD

**Issue by eshellman** [gutenbergbooks/git#9]
Although the current scope of work does not include adding downloads, it seems like something that could be needed in the future, if ebook generation is to be improved. Although we could easily change a repo's setting, it might be a 10-hour-long pain to do it for 50K repos.

https://github.com/gutenbergbooks/git/blob/master/init-pg-repo#L145

**Comment by acabal** [comment]
We could always script the Github API to automate setting downloads to true, should we decide to do that later.  We'd have to do some heavy work to integrate Github downloads into the PG build process anyway, so we could address that at that time.
